
# Frontier: not our lawset, shouldn't show up
# - type: guideEntry
#   id: SpaceLaw
#   name: guide-entry-rules-space-law
#   text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml"
#   children:
#   - SpaceLawCrimeList

# - type: guideEntry
#   id: SpaceLawCrimeList
#   name: guide-entry-rules-sl-crime-list
#   text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml"
# End Frontier
