using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Mono.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardPreviewMenu : FancyWindow
{
    private ShipyardPreviewSystem _previewSystem = default!;
    [Dependency] private EntityManager _entityMan = default!;

    public event Action<ButtonEventArgs>? OnExit;

    public ShipyardPreviewMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ExitButton.OnPressed += (args) => OnExit?.Invoke(args);

        _previewSystem = _entityMan.System<ShipyardPreviewSystem>();
    }

    public void UpdateMenu()
    {
        if (!_previewSystem.CurrentGrid.HasValue)
            return;

        var msg = new FormattedMessage(_previewSystem.GetGridData());

        ShipData.Text = msg.ToString();
        ShipName.Text = _entityMan.MetaQuery.Comp(_previewSystem.CurrentGrid.Value).EntityName;
    }
}

